ALTER TABLE tasks
  ADD COLUMN notes TEXT NOT NULL DEFAULT '',
  ADD COLUMN x REAL,
  ADD COLUMN y REAL;

CREATE TABLE subtasks (
  id SERIAL PRIMARY KEY,
  task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  dx REAL NOT NULL DEFAULT 180,
  dy REAL NOT NULL DEFAULT -140,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX subtasks_task_id_idx ON subtasks(task_id);